/// Arabic mapping for countries and major cities in Egypt 🇪🇬 and Saudi Arabia 🇸🇦
const Map<String, String> arabicLocationNames = {
  // ===== COUNTRIES =====
  'Egypt': 'مصر',
  'Saudi Arabia': 'المملكة العربية السعودية',
  'Kingdom of Saudi Arabia': 'المملكة العربية السعودية',

  // ===== EGYPT 🇪🇬 =====
  'Cairo': 'القاهرة',
  'Giza': 'الجيزة',
  'Alexandria': 'الإسكندرية',
  'Aswan': 'أسوان',
  'Luxor': 'الأقصر',
  'Suez': 'السويس',
  'Port Said': 'بورسعيد',
  'Ismailia': 'الإسماعيلية',
  'Tanta': 'طنطا',
  'Mansoura': 'المنصورة',
  'Zagazig': 'الزقازيق',
  'Minya': 'المنيا',
  'Beni Suef': 'بني سويف',
  'Faiyum': 'الفيوم',
  'Assiut': 'أسيوط',
  'Sohag': 'سوهاج',
  'Qena': 'قنا',
  'Hurghada': 'الغردقة',
  'Sharm El Sheikh': 'شرم الشيخ',
  'Damietta': 'دمياط',
  'Kafr El Sheikh': 'كفر الشيخ',
  'Beheira': 'البحيرة',
  'Sharqia': 'الشرقية',
  'Dakahlia': 'الدقهلية',
  'Monufia': 'المنوفية',
  'Qalyubia': 'القليوبية',
  'New Valley': 'الوادي الجديد',
  'Matrouh': 'مطروح',
  'North Sinai': 'شمال سيناء',
  'South Sinai': 'جنوب سيناء',

  // ===== SAUDI ARABIA 🇸🇦 =====
  'Riyadh': 'الرياض',
  'Jeddah': 'جدة',
  'Mecca': 'مكة المكرمة',
  'Medina': 'المدينة المنورة',
  'Dammam': 'الدمام',
  'Khobar': 'الخبر',
  'Dhahran': 'الظهران',
  'Taif': 'الطائف',
  'Tabuk': 'تبوك',
  'Hail': 'حائل',
  'Abha': 'أبها',
  'Khamis Mushait': 'خميس مشيط',
  'Najran': 'نجران',
  'Jazan': 'جازان',
  'Yanbu': 'ينبع',
  'Al Ula': 'العلا',
  'Al Baha': 'الباحة',
  'Arar': 'عرعر',
  'Sakaka': 'سكاكا',
  'Al Qatif': 'القطيف',
  'Al Hofuf': 'الهفوف',
  'Buraydah': 'بريدة',
  'Unaizah': 'عنيزة',
  'Ras Tanura': 'رأس تنورة',
  'Al Jubail': 'الجبيل',
  'Al Khafji': 'الخفجي',
  'Al Majmaah': 'المجمعة',
  'Wadi Ad Dawasir': 'وادي الدواسر',
  'Al Qunfudhah': 'القنفذة',
  'Al Lith': 'الليث',
  'Al Bahah': 'الباحة',
  'Qurayyat': 'القريات',
  'Turaif': 'طريف',
  'Al Dawadmi': 'الدوادمي',
  'Hotat Bani Tamim': 'حوطة بني تميم',
  'Al Zulfi': 'الزلفي',
  'Al Kharj': 'الخرج',
  'Thadiq': 'ثادق',
  'Shaqra': 'شقراء',
};
